# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Подготовка релиза и публикация в хабе

on:
  workflow_call:
    inputs:
      oscript_version:
        required: true
        type: string
    secrets:
      PUSH_TOKEN:
        required: false

env:
  PACKAGE_MASK: "*.ospx"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v4

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ inputs.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install

      - name: Сборка пакета
        run: opm build .

      - name: Заливка артефактов
        uses: actions/upload-artifact@v3
        with:
          name: package.zip
          path: ./${{ env.PACKAGE_MASK }}

      #- name: Заливка в релиз
      #  uses: AButler/upload-release-assets@v2.0.2
      #  with:
      #    files: ./${{ env.PACKAGE_MASK }}
      #    repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Публикация в hub.oscript.io
        shell: bash
        run: opm push -f ./${{ env.PACKAGE_MASK }} --token ${{ secrets.PUSH_TOKEN }} -c stable
 
