name: Тестирование

on: 
  workflow_call:
    inputs:
      oscript_version:
        required: true
        type: string
      test_script_path:
        required: false
        type: string
        default: ./tasks/test.os

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        oscript_version: 
          - ${{ inputs.oscript_version }}
        
    steps:
      - name: Актуализация
        uses: actions/checkout@v4

      - name: Установка свойств git
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.3
        with:
          version: ${{ matrix.oscript_version }}

      - name: Установка зависимостей
        run: |
          opm install opm
          opm install -l --dev
          
      - name: Тестирование
        run: oscript ${{ inputs.test_script_path}}
