# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Тестирование

on: 
  workflow_call:
    inputs:
      oscript_version:
        required: true
        type: string
      oscript_version2:
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: ${{ matrix.oscript_version }} !== ''
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        oscript_version:
          - ${{ inputs.oscript_version }}
          - ${{ inputs.oscript_version2 }}
        
    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v2

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install -l --dev
          
      # Задача тестирования, в результате ожидается успешное выполнение
      - name: Тестирование
        run: oscript ./tasks/test.os
