name: Тестирование

on: 
  workflow_call:
    inputs:
      oscript_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        oscript_version: 
          - ${{ inputs.oscript_version }}
        
    steps:
      - name: Актуализация
        uses: actions/checkout@v2

      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      - name: Установка зависимостей
        run: |
          opm install opm
          opm install -l --dev
          
      - name: Тестирование
        run: oscript ./tasks/test.os
